version: "3.8"

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8880:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
