services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lumina_net
volumes:
  redis_data:
networks:
  lumina_net:
    driver: bridge